/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f4',
        'surface-dim': '#dcdad5',
        'surface-bright': '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede9',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'surface-variant': '#e5e2dd',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#43474e',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f3f0eb',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-tint': '#465f86',
        primary: '#032448',
        'on-primary': '#ffffff',
        'primary-container': '#1f3a5f',
        'on-primary-container': '#8ba4cf',
        'inverse-primary': '#aec8f4',
        'primary-fixed': '#d5e3ff',
        'on-primary-fixed': '#001c3b',
        'primary-fixed-dim': '#aec8f4',
        'on-primary-fixed-variant': '#2d476d',
        secondary: '#9c431e',
        'on-secondary': '#ffffff',
        'secondary-container': '#fd8d61',
        'on-secondary-container': '#732601',
        'secondary-fixed': '#ffdbce',
        'on-secondary-fixed': '#380d00',
        'secondary-fixed-dim': '#ffb59a',
        'on-secondary-fixed-variant': '#7d2d07',
        tertiary: '#1e2430',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#343a47',
        'on-tertiary-container': '#9ea3b3',
        'tertiary-fixed': '#dde2f3',
        'tertiary-fixed-dim': '#c1c6d6',
        'on-tertiary-fixed': '#161c27',
        'on-tertiary-fixed-variant': '#414754',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf9f4',
        'on-background': '#1c1c19',
      },
      spacing: {
        margin: '3rem',
        gutter: '1.5rem',
        'space-2xl': '3rem',
        'space-xl': '2rem',
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1.25rem',
        'gutter-mobile': '1rem',
      },
      fontFamily: {
        display: ['"Source Serif 4"', 'serif'],
        'display-mobile': ['"Source Serif 4"', 'serif'],
        headline: ['"Source Serif 4"', 'serif'],
        'headline-lg': ['"Source Serif 4"', 'serif'],
        'headline-lg-mobile': ['"Source Serif 4"', 'serif'],
        'headline-md': ['"Source Serif 4"', 'serif'],
        'headline-sm': ['"Source Serif 4"', 'serif'],
        title: ['"Public Sans"', 'sans-serif'],
        body: ['"Public Sans"', 'sans-serif'],
        'body-lg': ['"Public Sans"', 'sans-serif'],
        'body-md': ['"Public Sans"', 'sans-serif'],
        'body-sm': ['"Public Sans"', 'sans-serif'],
        'label-md': ['"Public Sans"', 'sans-serif'],
        'label-sm': ['"Public Sans"', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'monospace'],
        'code-data': ['"IBM Plex Mono"', 'monospace'],
      },
    },
  },
  plugins: [],
};
